name: syncio_capstone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_tree_view: ^2.3.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.5
  comment_tree: ^0.3.0
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_displaymode: ^0.6.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^10.8.5
  flutter_treeview: ^1.0.7+1
  google_sign_in: ^6.2.2
  grpc: ^4.0.1
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  protobuf: ^3.1.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  video_player: ^2.9.2
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2

flutter_native_splash: 
  color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/
    - assets/icon/branding.png
    - assets/images/default_avatar.png
    - assets/icon/logo-narrow-spacing.png
  generate: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 400
          style: normal
        - asset: fonts/sf-pro-display/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
          style: normal
        - asset: fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYTHINITALIC.OTF
          weight: 100
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYULTRALIGHTITALIC.OTF
          weight: 200
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
          style: italic
        - asset: fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700
          style: normal
        - asset: fonts/sf-pro-display/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 800
          style: italic

